spring.application.name: bikini-bottom

log.enabled: true

test.controller:
  enabled: false
  url: /bikini-bottom/test

scheduler:
  enabled: true
  validation.cron: 0 * * * * *

integration:
  validation:
    url: http://localhost:8081
    kafka:
      enabled: true
      topic: bikini-checks
      server: localhost:29092
      clientId: client_id
      groupId: group_id

voron:
  address: addressOne, addressTwo
  on: true

redis:
  url: localhost
  port: 6379